### ISSUE TITLE
Help with the installation

### ISSUE THREAD

**Issue by gibro** [spacedeck/spacedeck-open#101]
node.js runs on my server in version 12. At which places do I have to change the default.json so that the service runs at the end under gibro.de? The IP of my server is: 185.26.156.74. 

Here are the data I have entered in the default.json:
{
  "team_name": "My Open Spacedeck",
  "contact_email": "support@example.org",

  "host": "https://gibro.de",
  "port": 9666,
  "endpoint": "http://gibro.de:9666",
  "invite_code": "top-sekrit",

  "storage_local_path": "./storage",
  "storage_local_db": "./database.sqlite",
  "storage_region": "eu-central-1",
  "storage_endpoint": "http://gibro.de:4572",
  "storage_bucket": "my_spacedeck_bucket",
  "storage_cdn": "/storage",

  "mongodb_host": "localhost",
  "redis_mock": true,
  "redis_host": "localhost",

  "phantom_api_secret": "very_secret_phantom_password",

  "mail_provider": "smtp",
  "mail_smtp_host": "your.smtp.host",
  "mail_smtp_port": 465,
  "mail_smtp_secure": true,
  "mail_smtp_require_tls": true,
  "mail_smtp_user": "your.smtp.user",
  "mail_smtp_pass": "your.secret.smtp.password"
}

I read here that only the most necessary things should be changed in the default.json. Should I comment out the rest? What about the database, do I have to create it or is it created automatically?

Thanks a lot
Guido

**Comment by gibro** [comment]
This appears, when i start spacedeck.js:

node spacedeck.js 
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'config'
Require stack:
- /var/www/virtual/guibro/html/models/db.js
- /var/www/virtual/guibro/html/spacedeck.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/var/www/virtual/guibro/html/models/db.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/var/www/virtual/guibro/html/spacedeck.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/virtual/guibro/html/models/db.js',
    '/var/www/virtual/guibro/html/spacedeck.js'
  ]
}

**Comment by gibro** [comment]
If i downgrade my node.js installation to 10, ich get this Message:
node spacedeck.js 
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/virtual/guibro/html/models/db.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/virtual/guibro/html/spacedeck.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by mntmn** [comment]
Hi, you probably forgot to run `npm install`: https://github.com/spacedeck/spacedeck-open#requirements-installation

**Comment by gibro** [comment]
That was a good idea, but now, after npm install i get the following message:
node spacedeck.js 
[2020-09-23T15:14:56.883Z] Booting Spacedeck Open… (environment: development)
[2020-09-23T15:14:58.433Z] [redis-mock] websockets subscribed to 3 topics.
[2020-09-23T15:14:58.436Z] createBucket null undefined
/var/www/virtual/guibro/html/spacedeck.js:135
    throw error;
    ^

Error: getaddrinfo ENOTFOUND https://gibro.de
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)

Do you know, what i have to do?

Best
Guido

**Comment by mntmn** [comment]
Change the value of `"host"` to `"127.0.0.1"` or `"0.0.0.0"` depending on your needs, without `https://`.

**Comment by gibro** [comment]
Thanks a lot, i get a success message:
/ http:9666 => OK, listening: PID 19662, /usr/bin/node spacedeck.js
and 
... [2020-09-23T19:49:43.301Z] Executing (default): SELECT `name` FROM `SequelizeMeta` AS `SequelizeMeta` ORDER BY `SequelizeMeta`.`name` ASC;
[2020-09-23T19:49:43.307Z] Migration complete up!

But if i start the Webseite under https://gibro.de:9666 i get an Error in my Browser. And the Website redirected always to https? Is there a workaround to run spacedeck under https?

Best
Guido

**Comment by gibro** [comment]
Now it runs with gibro.de:443.

Thanks for all your help
Guido

**Comment by mntmn** [comment]
Cool, glad that it worked.

I realize it might not be good that our company address is now in the footer of your website, though. I should remove that from the repository.
