### ISSUE TITLE
node spacedeck.js returns error

### ISSUE THREAD

**Issue by tihfbrugge** [spacedeck/spacedeck-open#131]
Hello
I'm a total noob but want to test spacedeck to use it at our school. 
Now when I enter 'node spacedeck.js' I get this error: 
`[2020-11-19T12:35:26.333Z] Booting Spacedeck Open… (environment: development)
internal/modules/cjs/loader.js:438
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in c:\Program Files\nodejs\node_modules\uuid\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (c:\Program Files\nodejs\spacedeck-open-mnt\routes\api\users.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (c:\Program Files\nodejs\spacedeck-open-mnt\spacedeck.js:81:23) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}`

Can someone help me to fix this issue?
Thanks in advance.

**Comment by juliandavidmr** [comment]
Try:

- Verify that you have installed node >= 12
- Remove package-lock.json
- npm install

**Comment by tihfbrugge** [comment]
Same problem.

**Comment by tihfbrugge** [comment]
Problem solved. Localhost is running and spacedeck opens. But can't login. 
Probably need to add a record in sql?

**Comment by juliandavidmr** [comment]
You need to register an user using `top-sekrit` as the invitation code.

**Comment by tihfbrugge** [comment]
Thanks! Up and running!
