### ISSUE TITLE
PDF import not working

### ISSUE THREAD

**Issue by buerkelr** [spacedeck/spacedeck-open#19]
When importing a PDF file (grid import) the spacedeck server crashes with the following error:

/root/spacedeck-open/routes/api/spaces.js:469
                  var a = new Artifact({
                          ^

ReferenceError: Artifact is not defined
    at gm.<anonymous> (/root/spacedeck-open/routes/api/spaces.js:469:27)
    at gm.emit (events.js:180:13)
    at gm.<anonymous> (/root/spacedeck-open/node_modules/gm/lib/getters.js:82:14)
    at cb (/root/spacedeck-open/node_modules/gm/lib/command.js:322:16)
    at ChildProcess.onExit (/root/spacedeck-open/node_modules/gm/lib/command.js:305:9)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

**My system:**
- linux server with CentOS 7.4
- nodejs http server: SSL port 443
- development version of spacedeck-open
- no AWS S3
- GPL Ghostscript 9.07 (2013-02-14)

**Comment by mntmn** [comment]
Thanks for reporting! I just pushed a fix. Please pull and try again.

**Comment by buerkelr** [comment]
PDF grid import is working now. Thanks!

But when doing a grid import with zones then another error happens:


[2018-05-04T07:43:47.330Z] [s3]/tmp/1920_EMLPDigitalConference2018LCBCOLDRAFT-page-004.jpeg to /storage/s366d2277-65db-4148-8c3e-137247dbb8a6/a9ee5e67c-b464-4f81-9322-1019bdd3c29a/1920_EMLPDigitalConference2018LCBCOLDRAFT-page-004.jpeg
[2018-05-04T07:43:47.338Z] Executing (default): UPDATE `artifacts` SET `updated_at`='2018-05-04 07:43:47.332 +00:00',`mime`='image/jpeg',`w`=320,`h`=226,`state`='idle',`payload_size`=538572,`payload_thumbnail_web_uri`='/storage/s366d2277-65db-4148-8c3e-137247dbb8a6/a9ee5e67c-b464-4f81-9322-1019bdd3c29a/320_EMLPDigitalConference2018LCBCOLDRAFT-page-004.jpeg',`payload_thumbnail_medium_uri`='/storage/s366d2277-65db-4148-8c3e-137247dbb8a6/a9ee5e67c-b464-4f81-9322-1019bdd3c29a/800_EMLPDigitalConference2018LCBCOLDRAFT-page-004.jpeg',`payload_thumbnail_big_uri`='/storage/s366d2277-65db-4148-8c3e-137247dbb8a6/a9ee5e67c-b464-4f81-9322-1019bdd3c29a/1920_EMLPDigitalConference2018LCBCOLDRAFT-page-004.jpeg',`payload_uri`='/storage/s366d2277-65db-4148-8c3e-137247dbb8a6/a9ee5e67c-b464-4f81-9322-1019bdd3c29a/EMLPDigitalConference2018LCBCOLDRAFT-page-004.jpeg',`updatedAt`='2018-05-04 07:43:47.332 +00:00' WHERE `_id` = '9ee5e67c-b464-4f81-9322-1019bdd3c29a'
[2018-05-04T07:43:47.550Z] successfully deleted /tmp/EMLPDigitalConference2018LCBCOLDRAFT/EMLPDigitalConference2018LCBCOLDRAFT-page-004.jpeg
/root/spacedeck-open/routes/api/spaces.js:491
                            w: artifact.board.w + 20,
                                              ^

TypeError: Cannot read property 'w' of undefined
    at payloadConverter.convert (/root/spacedeck-open/routes/api/spaces.js:491:47)
    at /root/spacedeck-open/helpers/artifact_converter.js:275:11
    at FSReqWrap.oncomplete (fs.js:153:20)

**Comment by mntmn** [comment]
Fixed, please try again.
