### ISSUE TITLE
Deleting space/user is not possible

### ISSUE THREAD

**Issue by buerkelr** [spacedeck/spacedeck-open#23]
When trying to delete a space or user the spacedeck server prints the following error:

[2018-05-14T11:22:38.131Z] getUserRoleInSpace 69b1b428-3c9d-4f93-8a42-8f6ad43ea9fb fed40758-4a5a-4a7b-a9ee-46774f8e516b ca48697a-1993-4b9e-bda4-df36a030337f
[2018-05-14T11:22:38.135Z] Executing (default): DELETE FROM `spaces` WHERE rowid IN (SELECT rowid FROM `spaces` WHERE `_id` = '69b1b428-3c9d-4f93-8a42-8f6ad43ea9fb' LIMIT 1)
[2018-05-14T11:22:38.144Z] Unhandled rejection SequelizeForeignKeyConstraintError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
    at Query.formatError (/root/spacedeck-open/node_modules/sequelize/lib/dialects/sqlite/query.js:374:18)
    at Statement.afterExecute (/root/spacedeck-open/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at Statement.replacement (/root/spacedeck-open/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.replacement (/root/spacedeck-open/node_modules/sqlite3/lib/trace.js:19:31)

**My system:**
- linux server with CentOS 7.4
- nodejs http server: SSL port 443
- development version of spacedeck-open
- no AWS S3
- GPL Ghostscript 9.07 (2013-02-14)
- nodejs-version:   9.11.1
- nodejs:   sqlite3@4.0.0

**Comment by mntmn** [comment]
Confirmed.
