### ISSUE TITLE
Have you ever tested the `Dockerfile`?

### ISSUE THREAD

**Issue by aboettger-tuhh** [spacedeck/spacedeck-open#24]
Problem:
```
Step 19/22 : RUN gulp all
 ---> Running in 7b5af99f7b62
[04:12:29] Local gulp not found in /usr/src/app
[04:12:29] Try running: npm install gulp
The command '/bin/sh -c /usr/local/bin/gulp all' returned a non-zero code: 1
ERROR: Job failed: Process exited with: 1. Reason was:  ()
```
Solution:
```
RUN npm install --save-dev gulp
```

Next problem:
```
$ gulp all
module.js:472
    throw err;
    ^

Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/Gulpfile.js:2:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Solution:

```
npm install gulp-sass
```

Next Problem:
```
$ gulp all
module.js:472
    throw err;
    ^

Error: Cannot find module 'gulp-concat'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/Gulpfile.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Solution
```
npm install gulp-concat
```

Next problem:
```
$gulp all
[07:52:22] Using gulpfile /usr/src/app/Gulpfile.js
[07:52:22] Task 'all' is not in your gulpfile
[07:52:22] Please check the documentation for proper gulpfile formatting
```

Are you kidding me???

**Comment by mntmn** [comment]
Sorry, the Dockerfile is totally outdated and has to be rewritten. PRs welcome!

**Comment by aboettger-tuhh** [comment]
@mntmn  I need a Docker-based installation for the TU Hamburg. Is there a working installation guide? With that I can make a Dockerfile myself. I can then gladly make the result available to you.

**Comment by mntmn** [comment]
Edit: audiowaveform is actually not a debian package. There is an ubuntu package and source available here https://github.com/bbc/audiowaveform
But you need that only if you want to upload audio files and have their waveforms rendered.

**Comment by aboettger-tuhh** [comment]
Cool, thank you :D

Yes, `npm install` and `node spacedeck.js` works. I have a running container.
A problem is, `NODE_ENV production` doesn't works. I have to use `NODE_ENV development`.

The next things:

- I want to use something other than sqlite. 
- Which directories need to be backed up?
- How can I configure a mail server?

**Comment by mntmn** [comment]
How is it going here?

**Comment by mntmn** [comment]
The email functionality is now fixed in master. Any news regarding the dockerfile etc.?
