### ISSUE TITLE
TypeError: db.User.create(...).error is not a function

### ISSUE THREAD

**Issue by vinyll** [spacedeck/spacedeck-open#255]
1. Running with Docker and going to http://localhost:9666/signup
2. Filling the form with the invite code `top-sekrit` and submitting

Here's the Docker output before crashing:

```
spacedeck  | [2023-01-18T21:37:57.404Z] Executing (default): SELECT `_id`, `email`, `password_hash`, `nickname`, `avatar_original_uri`, `avatar_thumb_uri`, `confirmation_token`, `password_reset_token`, `api_token`, `home_folder_id`, `prefs_language`, `prefs_email_notifications`, `prefs_email_digest`, `created_at`, `updated_at`, `createdAt`, `updatedAt` FROM `users` AS `user` WHERE `user`.`email` = 'me@here.net';
spacedeck  | /app/routes/api/users.js:87
spacedeck  |             .error(err => {
spacedeck  |              ^
spacedeck  | 
spacedeck  | TypeError: db.User.create(...).error is not a function
spacedeck  |     at AsyncWrap.<anonymous> (/app/routes/api/users.js:87:14)
spacedeck  |     at AsyncWrap.wrap.ondone (internal/crypto/random.js:57:8)
```

**Comment by mntmn** [comment]
fixed in 43577337aa69df2f6a3c8052ae1092e974e88b24
