### ISSUE TITLE
Redirecting on real server

### ISSUE THREAD

**Issue by inf265** [spacedeck/spacedeck-open#36]
Hi,
I installed spacedeck on a server in the internet, changed "endpoint" to http://<domainname>:9666.
When I open the site on my browser at home (not on the webserver), I get the initial page with "Registrieren" ... "Anmelden" but whatever I click from the both, it redirects my browser to http://localhost:9666.
Any help ?
BR
Frédéric

**Comment by mntmn** [comment]
Hi,

you need to configure the "endpoint":
https://github.com/spacedeck/spacedeck-open/blob/master/config/default.json#L5

Hope that helps!
Cheers
Lukas

**Comment by inf265** [comment]
Hi,
yes I did that already but not on master.
So I cehckout out master from today, changed default.json as you said and tried to start spacedeck:

```
fmetz@minka:~/spacedeck-open$ node spacedeck.js 
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'umzug'
Require stack:
- /home/fmetz/spacedeck-open/models/db.js
- /home/fmetz/spacedeck-open/spacedeck.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/fmetz/spacedeck-open/models/db.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/fmetz/spacedeck-open/models/db.js',
    '/home/fmetz/spacedeck-open/spacedeck.js'
  ]
}
fmetz@minka:~/spacedeck-open$ git pull
Already up-to-date.
fmetz@minka:~/spacedeck-open$ node --version
v13.11.0
fmetz@minka:~/spacedeck-open$ 

```

**Comment by mntmn** [comment]
Hi, can you try the new branch *mnt*? It has many new fixes and cleanups.

Also, remember to do a "npm install" after pulling.
