### ISSUE TITLE
ImageMagick install instructions for Linux

### ISSUE THREAD

**Issue by osresearch** [spacedeck/spacedeck-open#37]
Issue #12 suggests that GraphicsMagick needs to be installed and links to the Windows install instructions.  On an Ubuntu 18.04 machine with ImageMagick installed and both `identify` and `convert` in the `$PATH`, uploading images results in:

```
gm: Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "/tmp/49315841813_d21d303cfa_k.jpg" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/home/hudson/build/spacedeck-open/node_modules/gm/lib/command.js:232:12)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19) undefined
POST /api/spaces/afa2dd39-f0db-4a7e-bf8b-7cc6461890c0/artifacts/9f1c510e-1032-416c-a39f-e61773c401e2/payload?filename=49315841813_d21d303cfa_k.jpg 400 209.143 ms - 2
```

Running that command in the shell produces the expected result:
```
"identify" "-ping" "-format" "%wx%h" "/tmp/49315841813_d21d303cfa_k.jpg
2048x1536
```

Separately, a UI improvement would be to cancel the upload and let the user know it failed in the case that the server couldn't process the image. Currently the client shows an hourglass that never finishes, rather than reporting the 400 error:

![image](https://user-images.githubusercontent.com/3068843/77070384-679fa180-69ea-11ea-8703-8deab575798b.png)

**Comment by osresearch** [comment]
Ah, I see the problem -- spacedeck is invoking `gm identify ....`, not `identify ...`.  Installing GraphicsMagick with `sudo apt install graphicsmagick` provides `gm` and allows it to work. This would be useful to add to the `README.md` along with the ffmpeg dependency.
