### ISSUE TITLE
SMTP sending failed

### ISSUE THREAD

**Issue by aljosahafner** [spacedeck/spacedeck-open#38]
Hey,
I am trying to setup the E-mail sending by SMTP. However, I am getting the following error: 

`POST /api/users/bb345eca-65cb-4bbf-bfe6-b3869716df58/confirm 201 78.658 ms - 7
[2020-04-04T19:10:36.977Z] Error sending email: { Error: Hostname/IP doesn't match certificate's altnames: "Host: . is not in the cert's altnames: DNS:*, DNS:"
    at Object.checkServerIdentity (tls.js:223:17)
    at TLSSocket.<anonymous> (_tls_wrap.js:1111:29)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
  reason: 'Host:  is not in the cert\'s altnames: DNS:*, DNS:',
  host: '',
  cert: 
   { subject: { OU: [Array], CN: '*' },
     issuer: 
      { C: 'GB',
        ST: 'Greater Manchester',
        L: 'Salford',
        O: 'COMODO CA Limited',
        CN: 'COMODO RSA Domain Validation Secure Server CA' },
     subjectaltname: 'DNS:*, DNS:',
     infoAccess: { 'CA Issuers - URI': [Array], 'OCSP - URI': [Array] },
     modulus: 'CBD9B08056EFEFA14C09FE5FFF27281EC5D4301B6BD6E06E98F024C6F16179962365077EC772D1B1C1CE8BF15E9FCCF405029FBFA477F4E818398585318F596EA38926A0709EC8279297C2F79E188A6C7157E984F0C0D1FDEEEE3120DA1F707BFB69AC0A10B3B647EF1666C71A666076685740E1B83D0158D6011EF38A8DFB8AB3750B813BF7930368D26097BE16A71AEDC58E60B227B491885FE64A79297AEB08AA46B4EBB007F508029468B999F450F807D9EFDAC7769F469C593F9730E67FBF4FDFB3293898B93804A77B9163A31620F1667DFB5D8BD6F2E2F47131C606BF6EF12320A2C07411834081F35B8A87F6FFE4C5EB3A87A8CF96477131B8D85DFD',
     exponent: '0x10001',
     valid_from: 'Jul 19 00:00:00 2017 GMT',
     valid_to: 'Jul 18 23:59:59 2020 GMT',
     fingerprint: 'E0:D6:61:61:D9:F6:F4:C1:49:43:D2:F1:3E:93:FE:5A:D8:01:D6:D7',
     ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],
     serialNumber: 'D532DC23F08853259FA81D4FA0874678',
     raw: <Buffer 30 82 05 5b 30 82 04 43 a0 03 02 01 02 02 11 00 d5 32 dc 23 f0 88 53 25 9f a8 1d 4f a0 87 46 78 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 81 90 ... > },
  code: 'ESOCKET',
  command: 'CONN' }`

What can I do to make it work?

**Comment by webdevisme** [comment]
I'm no expert in spacedeck or email setup, but it sounds like an issue with
your SMTP servers SSL certificates are not including the domain your using
for the email.
Try checking the registered certificates in your server and ensuring that
they include the domain you're using. If not, either ad it to a current
certificate, or add a new one.
Maybe testing with another email app will help diagnose the problem a
little more.

**Comment by bernhardreiter** [comment]
If you know what you are doing, you maybe able to play with the mailserver settings in config.default.json.

**Comment by mntmn** [comment]
I'm working on this now, I'm currently getting the following when trying to send via SendGrid:

```
Error sending email: { [Error: 140665195590208:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:332:
] code: 'ECONNECTION', command: 'CONN' }
```

**Comment by mntmn** [comment]
Ah, my error was because I wasn't connecting to the encrypted port 465.

The following config works for me, at least with sendgrid, on the *mnt* branch:

```
  "mail_provider": "smtp",
  "mail_smtp_host": "smtp.sendgrid.net",
  "mail_smtp_port": 465,
  "mail_smtp_secure": true,
  "mail_smtp_require_tls": true,
  "mail_smtp_user": "apikey",
  "mail_smtp_pass": "secret-api-key"
```

Can you try switching to the mnt branch and post your smtp settings here (without your password)?

**Comment by mntmn** [comment]
Closing because of inactivity, mail sending works on spacedeck.com with above setup.
