### ISSUE TITLE
SQLITE_ERROR: duplicate column name: api_token

### ISSUE THREAD

**Issue by ram95014** [spacedeck/spacedeck-open#58]
I get the following error when I launch spacedeck-open:
Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: duplicate column name: api_token
    at Query.formatError (/Users/ram/Git/spacedeck-open/node_modules/sequelize/lib/dialects/sqlite/query.js:431:16)
    at afterExecute (/Users/ram/Git/spacedeck-open/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at wrappedAfterExecute (/Users/ram/Git/spacedeck-open/node_modules/sequelize/lib/dialects/sqlite/query.js:256:39)
    at replacement (/Users/ram/Git/spacedeck-open/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/Users/ram/Git/spacedeck-open/node_modules/sqlite3/lib/sqlite3.js:14:21)

Please help.

**Comment by jainal09** [comment]
having, the same issue, please help

**Comment by exit-failure** [comment]
It semms, I'm having the same problem:

[2020-05-27T17:17:19.065Z] Booting Spacedeck Open… (environment: development)
[2020-05-27T17:17:19.456Z] [redis-mock] websockets subscribed to 3 topics.
[2020-05-27T17:17:19.457Z] Spacedeck Open listening at http://:::9666
[2020-05-27T17:17:19.463Z] createBucket null undefined
[2020-05-27T17:17:19.465Z] Executing (default): CREATE TABLE IF NOT EXISTS `users` (`_id` VARCHAR(255) PRIMARY KEY, `email` VARCHAR(255), `password_hash` VARCHAR(255), `nickname` VARCHAR(255), `avatar_original_uri` VARCHAR(255), `avatar_thumb_uri` VARCHAR(255), `confirmation_token` VARCHAR(255), `password_reset_token` VARCHAR(255), `api_token` VARCHAR(255), `home_folder_id` VARCHAR(255), `prefs_language` VARCHAR(255), `prefs_email_notifications` VARCHAR(255), `prefs_email_digest` VARCHAR(255), `created_at` DATETIME, `updated_at` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
[2020-05-27T17:17:19.469Z] Executing (default): PRAGMA INDEX_LIST(`users`)
[2020-05-27T17:17:19.470Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_users_1`)
[2020-05-27T17:17:19.471Z] Executing (default): CREATE TABLE IF NOT EXISTS `sessions` (`token` VARCHAR(255) PRIMARY KEY, `user_id` VARCHAR(255), `expires` DATETIME, `created_at` DATETIME, `device` VARCHAR(255), `ip` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
[2020-05-27T17:17:19.472Z] Executing (default): PRAGMA INDEX_LIST(`sessions`)
[2020-05-27T17:17:19.472Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_sessions_1`)
[2020-05-27T17:17:19.474Z] Executing (default): CREATE TABLE IF NOT EXISTS `spaces` (`_id` VARCHAR(255) PRIMARY KEY, `name` VARCHAR(255), `space_type` VARCHAR(255) DEFAULT 'space', `creator_id` VARCHAR(255) REFERENCES `users` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `parent_space_id` VARCHAR(255), `access_mode` VARCHAR(255), `password` VARCHAR(255), `edit_hash` VARCHAR(255), `edit_slug` VARCHAR(255), `editors_locking` TINYINT(1), `thumbnail_uri` VARCHAR(255), `width` INTEGER, `height` INTEGER, `background_color` VARCHAR(255), `background_uri` VARCHAR(255), `created_at` DATETIME, `updated_at` DATETIME, `thumbnail_url` VARCHAR(255), `thumbnail_updated_at` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
[2020-05-27T17:17:19.474Z] Executing (default): PRAGMA INDEX_LIST(`spaces`)
[2020-05-27T17:17:19.475Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_spaces_1`)
[2020-05-27T17:17:19.476Z] Executing (default): CREATE TABLE IF NOT EXISTS `memberships` (`_id` VARCHAR(255) PRIMARY KEY, `space_id` VARCHAR(255) REFERENCES `spaces` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `user_id` VARCHAR(255) REFERENCES `users` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `role` VARCHAR(255), `code` VARCHAR(255), `state` VARCHAR(255) DEFAULT 'pending', `email_invited` VARCHAR(255), `created_at` DATETIME, `updated_at` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
[2020-05-27T17:17:19.476Z] Executing (default): PRAGMA INDEX_LIST(`memberships`)
[2020-05-27T17:17:19.476Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_memberships_1`)
[2020-05-27T17:17:19.477Z] Executing (default): CREATE TABLE IF NOT EXISTS `messages` (`_id` VARCHAR(255) PRIMARY KEY, `space_id` VARCHAR(255) REFERENCES `spaces` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `user_id` VARCHAR(255) REFERENCES `users` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `editor_name` VARCHAR(255), `message` TEXT, `created_at` DATETIME, `updated_at` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
[2020-05-27T17:17:19.478Z] Executing (default): PRAGMA INDEX_LIST(`messages`)
[2020-05-27T17:17:19.478Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_messages_1`)
[2020-05-27T17:17:19.480Z] Executing (default): CREATE TABLE IF NOT EXISTS `artifacts` (`_id` VARCHAR(255) PRIMARY KEY, `space_id` VARCHAR(255) REFERENCES `spaces` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `user_id` VARCHAR(255) REFERENCES `users` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `mime` VARCHAR(255), `thumbnail_uri` VARCHAR(255), `last_update_user_id` VARCHAR(255), `editor_name` VARCHAR(255), `last_update_editor_name` VARCHAR(255), `description` TEXT, `state` VARCHAR(255), `title` VARCHAR(255), `tags` TEXT, `search_text` VARCHAR(255), `link_uri` VARCHAR(255), `play_from` DECIMAL, `play_to` DECIMAL, `x` DECIMAL, `y` DECIMAL, `z` DECIMAL, `r` DECIMAL, `w` DECIMAL, `h` DECIMAL, `control_points` TEXT, `group` VARCHAR(255), `locked` TINYINT(1), `payload_uri` VARCHAR(255), `payload_thumbnail_web_uri` VARCHAR(255), `payload_thumbnail_medium_uri` VARCHAR(255), `payload_thumbnail_big_uri` VARCHAR(255), `payload_size` INTEGER, `fill_color` VARCHAR(255), `stroke_color` VARCHAR(255), `text_color` VARCHAR(255), `stroke` DECIMAL, `stroke_style` VARCHAR(255), `alpha` DECIMAL, `order` INTEGER, `crop_x` INTEGER, `crop_y` INTEGER, `crop_w` INTEGER, `crop_h` INTEGER, `shape` VARCHAR(255), `shape_svg` VARCHAR(255), `padding_left` INTEGER, `padding_right` INTEGER, `padding_top` INTEGER, `padding_bottom` INTEGER, `margin_left` INTEGER, `margin_right` INTEGER, `margin_top` INTEGER, `margin_bottom` INTEGER, `border_radius` INTEGER, `align` VARCHAR(255), `valign` VARCHAR(255), `brightness` DECIMAL, `contrast` DECIMAL, `saturation` DECIMAL, `blur` DECIMAL, `hue` DECIMAL, `opacity` DECIMAL, `payload_alternatives` TEXT, `created_at` DATETIME, `updated_at` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
[2020-05-27T17:17:19.480Z] Executing (default): PRAGMA INDEX_LIST(`artifacts`)
[2020-05-27T17:17:19.480Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_artifacts_1`)
[2020-05-27T17:17:19.485Z] Executing (default): CREATE TABLE IF NOT EXISTS `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY);
[2020-05-27T17:17:19.485Z] Executing (default): PRAGMA INDEX_LIST(`SequelizeMeta`)
[2020-05-27T17:17:19.486Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_SequelizeMeta_1`)
[2020-05-27T17:17:19.489Z] Executing (default): SELECT `name` FROM `SequelizeMeta` AS `SequelizeMeta` ORDER BY `SequelizeMeta`.`name` ASC;
[2020-05-27T17:17:19.493Z] Executing (default): CREATE TABLE IF NOT EXISTS `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY);
[2020-05-27T17:17:19.494Z] Executing (default): PRAGMA INDEX_LIST(`SequelizeMeta`)
[2020-05-27T17:17:19.494Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_SequelizeMeta_1`)
[2020-05-27T17:17:19.495Z] Executing (default): SELECT `name` FROM `SequelizeMeta` AS `SequelizeMeta` ORDER BY `SequelizeMeta`.`name` ASC;
[2020-05-27T17:17:19.498Z] Executing (default): ALTER TABLE `users` ADD `api_token` VARCHAR(255);
[2020-05-27T17:17:19.501Z] Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: duplicate column name: api_token
    at Query.formatError (/home/media/serv/spacedeck-open/node_modules/sequelize/lib/dialects/sqlite/query.js:431:16)
    at afterExecute (/home/media/serv/spacedeck-open/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at wrappedAfterExecute (/home/media/serv/spacedeck-open/node_modules/sequelize/lib/dialects/sqlite/query.js:256:39)
    at replacement (/home/media/serv/spacedeck-open/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/home/media/serv/spacedeck-open/node_modules/sqlite3/lib/sqlite3.js:14:21)

**Comment by sebastientaggart** [comment]
Same thing when running via `docker-compose.yml`:

```
spacedeck    | [2020-06-01T01:02:02.519Z] Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: duplicate column name: api_token
spacedeck    |     at Query.formatError (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:431:16)
spacedeck    |     at afterExecute (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
spacedeck    |     at wrappedAfterExecute (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:256:39)
spacedeck    |     at replacement (/app/node_modules/sqlite3/lib/trace.js:19:31)
spacedeck    |     at Statement.errBack (/app/node_modules/sqlite3/lib/sqlite3.js:14:21)
```

This is on first run, clean install.

**Comment by jp9573** [comment]
I face the same issue once I start the app. It doesn't break anything, I think it is giving that error because of empty database.
**HOW I SOLVED IT??**
Just open the [http://localhost:9666/](http://localhost:9666/) in your browser and you'll be able to create new account/sign-in and start using whiteboard.

It's is running absolutely well.. 👍

**Comment by yrammos** [comment]
I encounter the problem on Ubuntu 18.04 but, curiously, not on macOS—with the same `node`, `sqlite3`,  and `sequelize` versions on both platforms.

I addressed it by replacing `addColumn()` and `removeColumn()` with `add`changeColumn` in `models/migrations/02-users-add-api-token.js/. After replacing, the file contents are:

```js
'use strict';

module.exports = {
  up: function(migration, DataTypes) {
    return Promise.all([
      migration.changeColumn('users', 'api_token',
        {
          type: DataTypes.STRING
        }
      )
    ])
  },

  down: function(migration, DataTypes) {
    return Promise.all([
      migration.changeColumn('users', 'api_token',
        {
          type: Sequelize.STRING
        }
      )
    ])
  }
}
```

**Comment by badscrew** [comment]
Same error on clean install - is there a fix for that?

**Comment by yrammos** [comment]
@badscrew see my above for a solution that so far works here.

**Comment by mntmn** [comment]
@yrammos would you be able to make a PR with your solution?

**Comment by yrammos** [comment]
@mntmn PR submitted.
