### ISSUE TITLE
crash after video upload

### ISSUE THREAD

**Issue by bernhardreiter** [spacedeck/spacedeck-open#69]
Used the media upload to send a video (`fahrradkeller.mp4'). After converting it, spacedeck crashed on the server. (Tested with 0c5fa597e8c8325ec77a1061fae65497cea57f7b)

Restarting and looking at the space, the video is there now, so it must have something to do with the cleanup of the import, I guess.

Here is part of the log
```
[2020-06-15T08:46:21.638Z] [s3]/tmp/fahrradkeller.mp4.ogv to /storage/s45e
f378f-52f2-40be-bcf7-e3dcd49a0970/a83327ecd-5668-4fa0-8f34-bbf2bd511913/fahrradk
eller.mp4.ogv                                                            
[2020-06-15T08:46:21.639Z] null { mp4: 'org',                                   
  original: '/storage/fahrradkeller.mp4',                                 
  thumbnail:                                                                   
   '/storage/s45ef378f-52f2-40be-bcf7-e3dcd49a0970/a83327ecd-5668-4fa0-8f34-bbf2
bd511913/fahrradkeller.mp4.jpg',                                          
  ogg:                                                                         
   '/storage/s45ef378f-52f2-40be-bcf7-e3dcd49a0970/a83327ecd-5668-4fa0-8f34-bbf2
bd511913/fahrradkeller.mp4.ogv' }                                         
fs.js:114               
       throw err;                                                                      ^                                                                                                                                                           
Error: ENOENT: no such file or directory, stat '/tmp/fahrradkeller.mp4'  
    at Object.statSync (fs.js:855:3)                                            
    at /home/bern/spacedeck-open-git/helpers/artifact_converter.js:414:30        
    at /home/bern/spacedeck-open-git/node_modules/async/dist/async.js:3824:9     
    at /home/bern/spacedeck-open-git/node_modules/async/dist/async.js:460:16         at iterateeCallback (/home/bern/spacedeck-open-git/node_modules/async/dist/async.js:965:24)                                                                      at /home/bern/spacedeck-open-git/node_modules/async/dist/async.js:944:16     
    at /home/bern/spacedeck-open-git/node_modules/async/dist/async.js:3821:13        at apply (/home/bern/spacedeck-open-git/node_modules/async/dist/async.js:21:2
5)                                                                             
    at /home/bern/spacedeck-open-git/node_modules/async/dist/async.js:56:12      
    at /home/bern/spacedeck-open-git/helpers/artifact_converter.js:380:28       
    at /home/bern/spacedeck-open-git/helpers/uploader.js:79:11                  
    at done (/home/bern/spacedeck-open-git/node_modules/mock-aws-s3/lib/mock.js:3
89:14)                                                                          
    at WriteStream.<anonymous> (/home/bern/spacedeck-open-git/node_modules/mock-a
ws-s3/lib/mock.js:409:5)                                                        
    at WriteStream.emit (events.js:203:15)                                     
    at finishMaybe (_stream_writable.js:646:14)                                 
    at stream._final (_stream_writable.js:624:5)                               
    at WriteStream._final (internal/fs/streams.js:268:3)
    at callFinal (_stream_writable.js:617:10)                                   
    at process._tickCallback (internal/process/next_tick.js:63:19)  

ls /tmp/fahrradkeller.mp4      
ls: cannot access '/tmp/fahrradkeller.mp4': No such file or directory    
$ ls /tmp/                            
fahrradkeller.mp4.jpg                                                     
fahrradkeller.mp4.ogv    
```

**Comment by ductrinhhuu** [comment]
I got the same problem, and I was able to resolve it by installing ffmpeg. After that, I can upload mp3/mp4 normally

**Comment by bernhardreiter** [comment]
@ductrinhhuu thanks for commenting.

In my case ffmpeg is installed and some transformation is successfully happening (this is why I've suspected the cleanup process) but it is good to know that it works for you! :)

```
dpkg -l ffmpeg | tail -1
ii  ffmpeg         7:4.1.4-1~deb10u1 amd64        Tools for transcoding, streaming and playing of multimedia files
```

**Comment by ductrinhhuu** [comment]
Did you install ffmpeg by snap? If yes, try uninstall it, then install with apt. I first tried "snap install ffmpeg" with version 4.1.4, seems this version could not work for files inside /tmp (or /opt, /usr,...)
Good luck

**Comment by bernhardreiter** [comment]
No, this is Debian Buster, so just via apt from the official repository. :)  (Thanks again for caring.)

**Comment by mntmn** [comment]
Confirmed, I have to reload the browser to see the converting/converted video.

**Comment by mntmn** [comment]
I believe that this particular bug is fixed, btw, but the experience is still not good (no progress is seen during video conversion).

**Comment by tim-krieger** [comment]
I've to reload the page like described in #54 to play the video.

**Comment by mntmn** [comment]
This is fixed now. Can you confirm?

**Comment by bernhardreiter** [comment]
@mntmn thanks for the note. I appreciate the progress. Right now I am not looking into spacedeck for a while, so best would be if somebody else could confirm.

**Comment by tim-krieger** [comment]
I can confirm this. Thank you!
