### ISSUE TITLE
Issue when running spacedeck.js

### ISSUE THREAD

**Issue by shivshankarkeshari** [spacedeck/spacedeck-open#73]
I am new in node.js 
when I am running 

node spacedeck.js

getting error:

```
shiv@shiv-Inspiron-3542:~/Documents/Django_projects/free_style/spacedeck-open-mnt$ node spacedeck.js 
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'umzug'
Require stack:
- /home/shiv/Documents/Django_projects/free_style/spacedeck-open-mnt/models/db.js
- /home/shiv/Documents/Django_projects/free_style/spacedeck-open-mnt/spacedeck.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/shiv/Documents/Django_projects/free_style/spacedeck-open-mnt/models/db.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/shiv/Documents/Django_projects/free_style/spacedeck-open-mnt/models/db.js',
    '/home/shiv/Documents/Django_projects/free_style/spacedeck-open-mnt/spacedeck.js'
  ]
}

```

Is there any configuration I have to set before running spacedeck.js?

**Comment by yrammos** [comment]
You probably neglected to run `npm install` after cloning the repo.
