### ISSUE TITLE
Issue when running spacedeck.js - SequelizeDatabaseError: SQLITE_ERROR: duplicate column name: api_token

### ISSUE THREAD

**Issue by huberv** [spacedeck/spacedeck-open#74]
Hi all,

I just cloned the repository, ran `npm install` and then `node spacedeck.js`. Then I get the following error:

d:\Valentin\Arbeit\Code\IntelliJProjects\spacedeck-open>node spacedeck.js
[2020-07-08T07:55:04.921Z] Booting Spacedeck Open… (environment: development)
[2020-07-08T07:55:05.403Z] [redis-mock] websockets subscribed to 3 topics.
[2020-07-08T07:55:05.404Z] Spacedeck Open listening at http://:::9666
[2020-07-08T07:55:05.411Z] Executing (default): CREATE TABLE IF NOT EXISTS `users` (`_id` VARCHAR(255) PRIMARY KEY, `email` VARCHAR(255), `password_hash` VARCHAR(255), `nickname` VARCHAR(255), `avatar_original_uri` VARCHAR(255), `avatar_thumb_uri` VARCHAR(255), `confirmation_token` VARCHAR(255), `password_reset_token` VARCHAR(255), `api_token` VARCHAR(255), `home_folder_id` VARCHAR(255), `prefs_language` VARCHAR(255), `prefs_email_notifications` VARCHAR(255), `prefs_email_digest` VARCHAR(255), `created_at` DATETIME, `updated_at` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
[2020-07-08T07:55:05.414Z] createBucket null undefined
[2020-07-08T07:55:05.416Z] Executing (default): PRAGMA INDEX_LIST(`users`)
[2020-07-08T07:55:05.417Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_users_1`)
[2020-07-08T07:55:05.419Z] Executing (default): CREATE TABLE IF NOT EXISTS `sessions` (`token` VARCHAR(255) PRIMARY KEY, `user_id` VARCHAR(255), `expires` DATETIME, `created_at` DATETIME, `device` VARCHAR(255), `ip` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
[2020-07-08T07:55:05.420Z] Executing (default): PRAGMA INDEX_LIST(`sessions`)
[2020-07-08T07:55:05.421Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_sessions_1`)
[2020-07-08T07:55:05.422Z] Executing (default): CREATE TABLE IF NOT EXISTS `spaces` (`_id` VARCHAR(255) PRIMARY KEY, `name` VARCHAR(255), `space_type` VARCHAR(255) DEFAULT 'space', `creator_id` VARCHAR(255) REFERENCES `users` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `parent_space_id` VARCHAR(255), `access_mode` VARCHAR(255), `password` VARCHAR(255), `edit_hash` VARCHAR(255), `edit_slug` VARCHAR(255), `editors_locking` TINYINT(1), `thumbnail_uri` VARCHAR(255), `width` INTEGER, `height` INTEGER, `background_color` VARCHAR(255), `background_uri` VARCHAR(255), `created_at` DATETIME, `updated_at` DATETIME, `thumbnail_url` VARCHAR(255), `thumbnail_updated_at` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
[2020-07-08T07:55:05.423Z] Executing (default): PRAGMA INDEX_LIST(`spaces`)
[2020-07-08T07:55:05.424Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_spaces_1`)
[2020-07-08T07:55:05.425Z] Executing (default): CREATE TABLE IF NOT EXISTS `memberships` (`_id` VARCHAR(255) PRIMARY KEY, `space_id` VARCHAR(255) REFERENCES `spaces` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `user_id` VARCHAR(255) REFERENCES `users` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `role` VARCHAR(255), `code` VARCHAR(255), `state` VARCHAR(255) DEFAULT 'pending', `email_invited` VARCHAR(255), `created_at` DATETIME, `updated_at` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
[2020-07-08T07:55:05.426Z] Executing (default): PRAGMA INDEX_LIST(`memberships`)
[2020-07-08T07:55:05.427Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_memberships_1`)
[2020-07-08T07:55:05.428Z] Executing (default): CREATE TABLE IF NOT EXISTS `messages` (`_id` VARCHAR(255) PRIMARY KEY, `space_id` VARCHAR(255) REFERENCES `spaces` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `user_id` VARCHAR(255) REFERENCES `users` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `editor_name` VARCHAR(255), `message` TEXT, `created_at` DATETIME, `updated_at` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
[2020-07-08T07:55:05.429Z] Executing (default): PRAGMA INDEX_LIST(`messages`)
[2020-07-08T07:55:05.429Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_messages_1`)
[2020-07-08T07:55:05.431Z] Executing (default): CREATE TABLE IF NOT EXISTS `artifacts` (`_id` VARCHAR(255) PRIMARY KEY, `space_id` VARCHAR(255) REFERENCES `spaces` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `user_id` VARCHAR(255) REFERENCES `users` (`_id`) ON DELETE NO ACTION ON UPDATE CASCADE, `mime` VARCHAR(255), `thumbnail_uri` VARCHAR(255), `last_update_user_id` VARCHAR(255), `editor_name` VARCHAR(255), `last_update_editor_name` VARCHAR(255), `description` TEXT, `state` VARCHAR(255), `title` VARCHAR(255), `tags` TEXT, `search_text` VARCHAR(255), `link_uri` VARCHAR(255), `play_from` DECIMAL, `play_to` DECIMAL, `x` DECIMAL, `y` DECIMAL, `z` DECIMAL, `r` DECIMAL, `w` DECIMAL, `h` DECIMAL, `control_points` TEXT, `group` VARCHAR(255), `locked` TINYINT(1), `payload_uri` VARCHAR(255), `payload_thumbnail_web_uri` VARCHAR(255), `payload_thumbnail_medium_uri` VARCHAR(255), `payload_thumbnail_big_uri` VARCHAR(255), `payload_size` INTEGER, `fill_color` VARCHAR(255), `stroke_color` VARCHAR(255), `text_color` VARCHAR(255), `stroke` DECIMAL, `stroke_style` VARCHAR(255), `alpha` DECIMAL, `order` INTEGER, `crop_x` INTEGER, `crop_y` INTEGER, `crop_w` INTEGER, `crop_h` INTEGER, `shape` VARCHAR(255), `shape_svg` VARCHAR(255), `padding_left` INTEGER, `padding_right` INTEGER, `padding_top` INTEGER, `padding_bottom` INTEGER, `margin_left` INTEGER, `margin_right` INTEGER, `margin_top` INTEGER, `margin_bottom` INTEGER, `border_radius` INTEGER, `align` VARCHAR(255), `valign` VARCHAR(255), `brightness` DECIMAL, `contrast` DECIMAL, `saturation` DECIMAL, `blur` DECIMAL, `hue` DECIMAL, `opacity` DECIMAL, `payload_alternatives` TEXT, `created_at` DATETIME, `updated_at` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
[2020-07-08T07:55:05.433Z] Executing (default): PRAGMA INDEX_LIST(`artifacts`)
[2020-07-08T07:55:05.433Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_artifacts_1`)
[2020-07-08T07:55:05.438Z] Executing (default): CREATE TABLE IF NOT EXISTS `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY);
[2020-07-08T07:55:05.439Z] Executing (default): PRAGMA INDEX_LIST(`SequelizeMeta`)
[2020-07-08T07:55:05.439Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_SequelizeMeta_1`)
[2020-07-08T07:55:05.443Z] Executing (default): SELECT `name` FROM `SequelizeMeta` AS `SequelizeMeta` ORDER BY `SequelizeMeta`.`name` ASC;
[2020-07-08T07:55:05.448Z] Executing (default): CREATE TABLE IF NOT EXISTS `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY);
[2020-07-08T07:55:05.449Z] Executing (default): PRAGMA INDEX_LIST(`SequelizeMeta`)
[2020-07-08T07:55:05.450Z] Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_SequelizeMeta_1`)
[2020-07-08T07:55:05.451Z] Executing (default): SELECT `name` FROM `SequelizeMeta` AS `SequelizeMeta` ORDER BY `SequelizeMeta`.`name` ASC;
[2020-07-08T07:55:05.455Z] Executing (default): ALTER TABLE `users` ADD `api_token` VARCHAR(255);
[2020-07-08T07:55:05.457Z] Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: duplicate column name: api_token
    at Query.formatError (d:\Valentin\Arbeit\Code\IntelliJProjects\spacedeck-open\node_modules\sequelize\lib\dialects\sqlite\query.js:431:16)
    at afterExecute (d:\Valentin\Arbeit\Code\IntelliJProjects\spacedeck-open\node_modules\sequelize\lib\dialects\sqlite\query.js:119:32)
    at wrappedAfterExecute (d:\Valentin\Arbeit\Code\IntelliJProjects\spacedeck-open\node_modules\sequelize\lib\dialects\sqlite\query.js:256:39)
    at replacement (d:\Valentin\Arbeit\Code\IntelliJProjects\spacedeck-open\node_modules\sqlite3\lib\trace.js:19:31)
    at Statement.errBack (d:\Valentin\Arbeit\Code\IntelliJProjects\spacedeck-open\node_modules\sqlite3\lib\sqlite3.js:14:21)

-> do I need to do something to set up the database correctly before running spacedeck?

**Comment by servantofchaos** [comment]
Good news! This has already been solved:
**https://github.com/spacedeck/spacedeck-open/issues/58**

Follow @yrammos solution to update the file -> models/migrations/02-users-add-api-token.js

**Comment by huberv** [comment]
Ok, thanks for the fast response. Would be good to get https://github.com/spacedeck/spacedeck-open/issues/58 closed, however.
