### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by chainzz** [spacedeck/spacedeck-open#8]
I dont get redirected after logging in. I changed the gulp-sass version in the packages.json file to 3.1.0 because it isnt compatible with windows 10. How can I fix it?

**Comment by chainzz** [comment]
[2018-03-30T18:59:08.341Z] Email not sent: { CredentialsError: Missing credentials in config
    at ClientRequest.<anonymous> (/root/Desktop/spacedeck-open/node_modules/aws-sdk/lib/http/node.js:83:34)
    at ClientRequest.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:620:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: 2018-03-30T18:59:08.311Z,
  retryable: true,
  originalError: 
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     time: 2018-03-30T18:59:08.311Z,
     retryable: true,
     originalError: 
      { message: 'Connection timed out after 1000ms',
        code: 'TimeoutError',
        time: 2018-03-30T18:59:08.309Z,
        retryable: true } } }

**Comment by mntmn** [comment]
Did you solve the first issue?

Please don't post unrelated issues in the same ticket, but open a new ticket.

The error message complains about missing AWS SES (Simple Email Service) credentials, so it cannot send emails. If you set the env variable NODE_ENV=development, this error will go away. Example:

`export NODE_ENV=development`

And then start node.
